version: 'latest'
services:
  db:
    image: postgres  # Utilisez l'image PostgreSQL
    container_name: spb_postgres_container  # Changez le nom du conteneur si nécessaire
    environment:
      POSTGRES_USER: postgres  # Utilisateur par défaut de PostgreSQL
      POSTGRES_PASSWORD: Iyas.2020  # Mot de passe pour l'utilisateur PostgreSQL
      POSTGRES_DB: anime  # Nom de la base de données
    ports:
      - "5432:5432"  # PostgreSQL utilise le port 5432 par défaut
    volumes:
      - documents_data:/var/lib/postgresql/data  # Volume pour stocker les données PostgreSQL

volumes:
  documents_data: