version: 'latest'
services:
  db:
    image: postgres
    container_name: spb_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Iyas.2020
      POSTGRES_DB: anime
    ports:
      - "5432:5432"
    volumes:
      - documents_data:/var/lib/postgresql/data

volumes:
  documents_data: