server:
  error:
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anime
    username: postgres
    password: Iyas.2020
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: false
#    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE